default_platform(:ios)

platform :ios do
  desc "Export and upload OnlyGigz Musician to App Store Connect / TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "LMR88P32RH",
      issuer_id: "129157b0-afc6-4bd7-95a6-2614e9c4a838",
      key_filepath: "../../../AuthKey_LMR88P32RH.p8"
    )

    get_certificates(api_key: api_key)
    get_provisioning_profile(api_key: api_key, app_identifier: "com.onlygigz.musician")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      archive_path: "../build/ios/archive/Runner.xcarchive",
      skip_build_archive: true,
      export_options: {
        teamID: "9HTF2BKHQL",
        provisioningProfiles: {
          "com.onlygigz.musician" => "com.onlygigz.musician AppStore"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
